CREATE TABLE integration_system (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    system_code VARCHAR(64) NOT NULL UNIQUE,
    system_name VARCHAR(128) NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE integration_mapping (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    system_code VARCHAR(64) NOT NULL,
    local_field VARCHAR(128) NOT NULL,
    external_field VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sync_job (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    system_code VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP NULL
);

CREATE TABLE sync_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    sync_job_id BIGINT NULL,
    system_code VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    pulled_count INT NOT NULL DEFAULT 0,
    pushed_count INT NOT NULL DEFAULT 0,
    run_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message VARCHAR(500) NULL
);
